type RuleCategory = "canonical" | "type-level" | "external-boundary";
type RulePrinciple = "explicitness" | "immutability" | "both";

export type RuleEntry = {
  id: string;
  description: string;
  principle: RulePrinciple;
  category: RuleCategory;
  autoFixable: boolean;
  banned: string;
  canonical: string;
  eslintRule: string | null;
};

export const rules: RuleEntry[] = [
  // ── Variables ──────────────────────────────────────────────────────────
  {
    id: "var-to-const",
    description: "var and reassignment-free let must be const",
    principle: "explicitness",
    category: "canonical",
    autoFixable: true,
    banned: "var x, let x when never reassigned",
    canonical: "const x",
    eslintRule: "prefer-const",
  },
  {
    id: "no-var",
    description: "var declarations are banned",
    principle: "explicitness",
    category: "canonical",
    autoFixable: true,
    banned: "var x",
    canonical: "const x or let x",
    eslintRule: "no-var",
  },

  // ── Equality ───────────────────────────────────────────────────────────
  {
    id: "equality",
    description: "Loose equality operators are banned",
    principle: "explicitness",
    category: "canonical",
    autoFixable: true,
    banned: "== and !=",
    canonical: "=== and !==",
    eslintRule: "eqeqeq",
  },

  // ── Functions ──────────────────────────────────────────────────────────
  {
    id: "no-arrow-functions",
    description: "Arrow functions are banned everywhere including callbacks",
    principle: "explicitness",
    category: "canonical",
    autoFixable: true,
    banned: "() => expression or block",
    canonical: "function foo() {} declarations or function expressions",
    eslintRule: null,
  },
  {
    id: "no-default-parameters",
    description: "Default parameters are banned; check at top of function body",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "function foo(x = 0)",
    canonical: "explicit if check at top of function body",
    eslintRule: null,
  },
  {
    id: "no-async-without-await",
    description: "async function with no await must drop async or add await",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "async function with no await inside",
    canonical: "remove async or add await",
    eslintRule: null,
  },

  // ── Loops and Iteration ────────────────────────────────────────────────
  {
    id: "no-for-each",
    description: "forEach is banned; use indexed for loop",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "array.forEach(fn)",
    canonical: "for (let i = 0; i < array.length; i++)",
    eslintRule: null,
  },
  {
    id: "no-for-of",
    description: "for...of is banned; use indexed for loop",
    principle: "explicitness",
    category: "canonical",
    autoFixable: true,
    banned: "for (const x of array)",
    canonical: "for (let i = 0; i < array.length; i++)",
    eslintRule: null,
  },
  {
    id: "no-for-in",
    description: "for...in is banned; use Object.keys() with indexed for loop",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "for (const k in obj)",
    canonical: "for (let i = 0; i < keys.length; i++) with Object.keys()",
    eslintRule: null,
  },
  {
    id: "no-while",
    description: "while loop is banned; use for loop",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "while (cond)",
    canonical: "for (; cond;) or refactor",
    eslintRule: null,
  },
  {
    id: "no-do-while",
    description: "do...while loop is banned; use for loop",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "do { } while (cond)",
    canonical: "for loop with condition at top",
    eslintRule: null,
  },
  {
    id: "no-labeled-statements",
    description: "Labeled statements are banned; extract named function with early return",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "label: statement",
    canonical: "named function with early return",
    eslintRule: null,
  },
  {
    id: "no-break",
    description: "break is banned; extract named function with early return",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "break or break label",
    canonical: "named function with early return",
    eslintRule: null,
  },
  {
    id: "no-continue",
    description: "continue is banned; extract named function with early return",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "continue or continue label",
    canonical: "named function with early return",
    eslintRule: null,
  },

  // ── Array Mutation ─────────────────────────────────────────────────────
  {
    id: "no-array-push",
    description: "array.push() is banned; derive new array with spread",
    principle: "immutability",
    category: "canonical",
    autoFixable: true,
    banned: "array.push(x)",
    canonical: "const newArray = [...array, x]",
    eslintRule: null,
  },
  {
    id: "no-array-unshift",
    description: "array.unshift() is banned; derive new array with spread",
    principle: "immutability",
    category: "canonical",
    autoFixable: true,
    banned: "array.unshift(x)",
    canonical: "const newArray = [x, ...array]",
    eslintRule: null,
  },
  {
    id: "no-array-pop",
    description: "array.pop() is banned; use slice and explicit last element",
    principle: "both",
    category: "canonical",
    autoFixable: true,
    banned: "array.pop()",
    canonical: "const last = array[array.length - 1]; const rest = array.slice(0, -1)",
    eslintRule: null,
  },
  {
    id: "no-array-shift",
    description: "array.shift() is banned; use destructuring rest",
    principle: "immutability",
    category: "canonical",
    autoFixable: true,
    banned: "array.shift()",
    canonical: "const [first, ...rest] = array",
    eslintRule: null,
  },
  {
    id: "no-array-splice",
    description: "array.splice() is banned; use slice + spread reconstruction",
    principle: "immutability",
    category: "canonical",
    autoFixable: false,
    banned: "array.splice(...)",
    canonical: "slice + spread reconstruction",
    eslintRule: null,
  },
  {
    id: "no-array-index-assign",
    description: "array[i] = x is banned; derive new array with spread + slice",
    principle: "immutability",
    category: "canonical",
    autoFixable: false,
    banned: "array[i] = x",
    canonical: "const newArray = [...array.slice(0, i), x, ...array.slice(i + 1)]",
    eslintRule: null,
  },

  // ── Object Mutation ────────────────────────────────────────────────────
  {
    id: "no-property-assign",
    description: "obj.foo = x on an existing object is banned; derive new object",
    principle: "immutability",
    category: "canonical",
    autoFixable: false,
    banned: "obj.foo = x (mutation of existing object)",
    canonical: "const newObj = { ...obj, foo: x }",
    eslintRule: null,
  },
  {
    id: "no-delete",
    description: "delete obj.foo is banned; use object rest destructuring",
    principle: "immutability",
    category: "canonical",
    autoFixable: false,
    banned: "delete obj.foo",
    canonical: "const { foo, ...rest } = obj",
    eslintRule: null,
  },

  // ── Async ──────────────────────────────────────────────────────────────
  {
    id: "no-promise-then",
    description: ".then()/.catch() chains are banned; use async/await",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: ".then() / .catch() / .finally()",
    canonical: "async/await with try/catch/finally",
    eslintRule: null,
  },

  // ── Control Flow ───────────────────────────────────────────────────────
  {
    id: "no-ternary",
    description: "Ternary expression is banned; use if/else",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "x ? a : b",
    canonical: "if/else block",
    eslintRule: null,
  },
  {
    id: "no-switch",
    description: "switch statement is banned; use if/else or object lookup",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "switch (x) { case ... }",
    canonical: "if/else chain or object lookup",
    eslintRule: null,
  },
  {
    id: "no-logical-or-default",
    description: "|| for default value is banned; use explicit null/undefined check",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "x || defaultVal",
    canonical: "if (x === null || x === undefined) check",
    eslintRule: null,
  },
  {
    id: "no-logical-and-execution",
    description: "&& for conditional execution is banned; use explicit if block",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "x && fn()",
    canonical: "explicit if block",
    eslintRule: null,
  },
  {
    id: "no-nullish-coalescing",
    description: "?? nullish coalescing is banned; use explicit null/undefined check",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "x ?? defaultVal",
    canonical: "if (x === null || x === undefined) check",
    eslintRule: null,
  },
  {
    id: "no-optional-chaining",
    description: "?. optional chaining is banned; use explicit null/undefined check",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "x?.foo",
    canonical: "explicit null/undefined check before access",
    eslintRule: null,
  },

  // ── Shorthand Operators ────────────────────────────────────────────────
  {
    id: "no-increment",
    description: "++ and -- operators are banned; use explicit addition/subtraction",
    principle: "explicitness",
    category: "canonical",
    autoFixable: true,
    banned: "x++ / ++x / x-- / --x",
    canonical: "x = x + 1 / x = x - 1",
    eslintRule: "no-plusplus",
  },
  {
    id: "no-shorthand-operators",
    description: "Compound assignment operators are banned; use explicit form",
    principle: "explicitness",
    category: "canonical",
    autoFixable: true,
    banned: "x += n, x -= n, x *= n, x /= n",
    canonical: "x = x + n, x = x - n, x = x * n, x = x / n",
    eslintRule: "operator-assignment",
  },

  // ── Classes ────────────────────────────────────────────────────────────
  {
    id: "no-classes",
    description: "class syntax is banned; use factory functions",
    principle: "both",
    category: "canonical",
    autoFixable: false,
    banned: "class Foo { }",
    canonical: "factory function returning a plain object",
    eslintRule: "no-class-assign",
  },
  {
    id: "no-this",
    description: "this is banned; use explicit parameter passing",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "this.foo",
    canonical: "explicit parameter passing",
    eslintRule: null,
  },

  // ── Template Literals ──────────────────────────────────────────────────
  {
    id: "no-template-literals",
    description: "Template literals are banned; use string concatenation",
    principle: "explicitness",
    category: "canonical",
    autoFixable: true,
    banned: "`hello ${name}`",
    canonical: '"hello " + name',
    eslintRule: "no-template-curly-in-string",
  },

  // ── TypeScript ─────────────────────────────────────────────────────────
  {
    id: "no-any",
    description: "any is banned; use unknown with explicit narrowing",
    principle: "explicitness",
    category: "type-level",
    autoFixable: false,
    banned: "any",
    canonical: "unknown with explicit narrowing",
    eslintRule: null,
  },
  {
    id: "no-type-assertion",
    description: "Type assertion (as) without preceding type guard is banned",
    principle: "explicitness",
    category: "type-level",
    autoFixable: false,
    banned: "x as Foo without a preceding type guard",
    canonical: "narrow with if check first",
    eslintRule: null,
  },
  {
    id: "no-non-null-assertion",
    description: "Non-null assertion (!) is banned; use explicit null check",
    principle: "explicitness",
    category: "type-level",
    autoFixable: false,
    banned: "x!",
    canonical: "explicit null check",
    eslintRule: null,
  },
  {
    id: "no-bare-catch",
    description: "Bare catch (e) is banned; annotate as catch (e: unknown)",
    principle: "explicitness",
    category: "type-level",
    autoFixable: false,
    banned: "catch (e)",
    canonical: "catch (e: unknown)",
    eslintRule: null,
  },
  {
    id: "no-enum",
    description: "enum is banned; use as const object with derived type",
    principle: "explicitness",
    category: "type-level",
    autoFixable: false,
    banned: "enum Foo { }",
    canonical: "const Foo = { ... } as const; type Foo = typeof Foo[keyof typeof Foo]",
    eslintRule: null,
  },
  {
    id: "no-interface",
    description: "interface is banned; use type",
    principle: "explicitness",
    category: "type-level",
    autoFixable: false,
    banned: "interface Foo { }",
    canonical: "type Foo = { }",
    eslintRule: null,
  },
  {
    id: "no-namespace",
    description: "namespace/module keywords are banned; use ES module import/export",
    principle: "explicitness",
    category: "type-level",
    autoFixable: false,
    banned: "namespace Foo { } / module Foo { }",
    canonical: "ES module import/export",
    eslintRule: null,
  },
  {
    id: "require-return-type",
    description: "Exported functions must have explicit return type annotation",
    principle: "explicitness",
    category: "type-level",
    autoFixable: false,
    banned: "exported function without return type",
    canonical: "function foo(): ReturnType { }",
    eslintRule: null,
  },

  // ── Array Additional ───────────────────────────────────────────────────
  {
    id: "no-sort-without-comparator",
    description: "array.sort() without comparator is banned; always provide comparator",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "array.sort()",
    canonical: "array.sort(comparator)",
    eslintRule: null,
  },
  {
    id: "no-mutating-sort",
    description: "Mutating sort is banned; sort a copy with spread",
    principle: "immutability",
    category: "canonical",
    autoFixable: false,
    banned: "array.sort(comparator)",
    canonical: "[...array].sort(comparator)",
    eslintRule: null,
  },
  {
    id: "no-sparse-arrays",
    description: "Sparse arrays are banned; use explicit undefined",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "[1, , 3]",
    canonical: "[1, undefined, 3]",
    eslintRule: null,
  },
  {
    id: "no-array-constructor",
    description: "Array(n) constructor is banned; use fill or explicit literal",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "Array(n) or new Array(n)",
    canonical: "new Array(n).fill(value) or explicit literal",
    eslintRule: null,
  },

  // ── Object Additional ──────────────────────────────────────────────────
  {
    id: "no-has-own-property",
    description: "obj.hasOwnProperty(key) is banned; use Object.hasOwn()",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "obj.hasOwnProperty(key)",
    canonical: "Object.hasOwn(obj, key)",
    eslintRule: null,
  },

  // ── Promise Additional ─────────────────────────────────────────────────
  {
    id: "no-promise-race",
    description: "Promise.race() is banned; use Promise.allSettled() with explicit winner selection",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "Promise.race([...])",
    canonical: "Promise.allSettled([...]) + explicit winner selection logic",
    eslintRule: null,
  },
  {
    id: "no-promise-any",
    description: "Promise.any() is banned; use Promise.allSettled() with explicit first-success logic",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "Promise.any([...])",
    canonical: "Promise.allSettled([...]) + explicit first-success logic",
    eslintRule: null,
  },
  {
    id: "no-new-promise",
    description: "new Promise() constructor is banned except for wrapping callback-based APIs",
    principle: "explicitness",
    category: "external-boundary",
    autoFixable: false,
    banned: "new Promise((resolve, reject) => { })",
    canonical: "async function; exception: wrapping callback-based APIs at external boundaries",
    eslintRule: null,
  },
  {
    id: "no-unhandled-rejection",
    description: "Bare await outside try/catch is banned; always wrap in try/catch",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "await expr outside try/catch",
    canonical: "try { const x = await expr; } catch (e: unknown) { }",
    eslintRule: null,
  },

  // ── Spread ─────────────────────────────────────────────────────────────
  {
    id: "no-spread-args",
    description: "Spread in function calls is banned; use explicit argument passing",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "foo(...args)",
    canonical: "explicit argument passing",
    eslintRule: null,
  },

  // ── Destructuring ──────────────────────────────────────────────────────
  {
    id: "no-general-destructuring",
    description: "General destructuring is banned; use explicit property access",
    principle: "explicitness",
    category: "canonical",
    autoFixable: false,
    banned: "const { a, b } = obj (general destructuring)",
    canonical: "const a = obj.a; const b = obj.b",
    eslintRule: null,
  },
];
