/** @type {import('eslint').Linter.FlatConfig[]} */
// This file is auto-generated by scripts/generate.ts — do not edit by hand.
const config = [
  {
    rules: {
      "prefer-const": "error",
      "no-var": "error",
      "eqeqeq": ["error","always"],
      "no-plusplus": "error",
      "operator-assignment": ["error","never"],
      "no-class-assign": "error",
    },
  },
];

export default config;
