import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { rules } from "../src/rules/registry.js";
import { generateRulesMd } from "../src/generate/rules-md.js";
import { generateEslintConfig } from "../src/generate/eslint-config.js";

const REPO_ROOT = join(import.meta.dirname, "..");
const RULES_MD_PATH = join(REPO_ROOT, "RULES.md");
const ESLINT_CONFIG_PATH = join(REPO_ROOT, "eslint-config-bedrock.json");
const PACKAGE_INDEX_PATH = join(
  REPO_ROOT,
  "packages/eslint-config-bedrock/index.js",
);

// Rules with no direct ESLint equivalent, or where the ESLint rule checks the
// wrong thing and would produce false positives.
const OMITTED_ESLINT_RULES = new Set([
  // Flags interpolation inside regular strings — the inverse of what Bedrock bans.
  "no-template-curly-in-string",
]);

function generatePackageIndex(config: Record<string, unknown>): string {
  const lines: string[] = [];
  for (const [ruleName, value] of Object.entries(config)) {
    if (OMITTED_ESLINT_RULES.has(ruleName)) {
      continue;
    }
    lines.push(`      ${JSON.stringify(ruleName)}: ${JSON.stringify(value)},`);
  }
  const rulesBlock = lines.join("\n");
  return [
    `/** @type {import('eslint').Linter.FlatConfig[]} */`,
    `// This file is auto-generated by scripts/generate.ts — do not edit by hand.`,
    `const config = [`,
    `  {`,
    `    rules: {`,
    rulesBlock,
    `    },`,
    `  },`,
    `];`,
    ``,
    `export default config;`,
    ``,
  ].join("\n");
}

const rulesMd = generateRulesMd(rules);
writeFileSync(RULES_MD_PATH, rulesMd, "utf8");

const eslintConfig = generateEslintConfig(rules);
writeFileSync(ESLINT_CONFIG_PATH, JSON.stringify(eslintConfig, null, 2) + "\n", "utf8");

writeFileSync(PACKAGE_INDEX_PATH, generatePackageIndex(eslintConfig), "utf8");

console.log(
  "Generated RULES.md, eslint-config-bedrock.json, and packages/eslint-config-bedrock/index.js",
);
